CONTRIBUTING.md
README.md

The links work and are correct.
The readme is better and more descriptive.

Added links to github issue tracker etc, more detailed README.md

---

lib/ImageMetaTag/webpage.py

Issue #6: Commit #9 added a bug for multi-image pages

Corrected bug due to #9 subdirectores and multi-images

---

lib/ImageMetaTag/db.py

del_plots_from_dbfile can timeouts if concurrent delete processes are running.
This change means del_plots_from_dbfile now attempts to delete from the database in chunks with each chunk doing a full open/delete/commit/close process. This means it can do retries for timeouts properly. It also means that the sleep command can be removed, speeding up the process.

Allow delete_plots_from_dbfile to do retries on timeout/lock

---

_config.yml
docs/_config.yml

The web page needs time to be rebuilt on github though.

It appears that a .nojekyll file in the docs dir is what is needed

---

README.md

Add a link to the documentation from the README.md

---

javascript/imt_dropdown.js

A selector's value didn't account for when a slector doesn't use all of it's option (due to a higher selection filtering them).
Simple fix to check that and change the value.

Bugfix - stuck/broken selectors

---

ImageMetaTag/savefig.py

Premult replaced with nicer subroutine call, that doesn't need to use tostring or tobytes.
Thumbnail improved by moving it before the colour pallette manipulation.

Premult step simplified

---

ImageMetaTag/db.py
ImageMetaTag/img_dict.py
ImageMetaTag/savefig.py
test.py

Also adds better db error trapping to deal with no database tables.

Enable image metadata tags to contain SQL special characters.

---

setup.py

Now installs using  python2.7 setup.py install --user

Added data files for the javascript

---

ImageMetaTag/db.py

Stops occasional failures where a db file was created and didn't complete properly (system crash, killed process etc.) leaving an empty file.

Database read will create table if the db file does not have it.

---

ImageMetaTag/savefig.py
test.py

Bugfix to verbose image_postproc

---

ImageMetaTag/__init__.py
ImageMetaTag/javascript/imt_dropdown.js
docs/source/conf.py
setup.py

Changed setup.py so it might work on windows.
Updated version number as this needs to be a release to test the conda-forge recipe.
No API change so documentation not updated.

Tweak to setup, so it might work on windows.

---

release_process

Added the rest of the details for the release_process notes file.

Release process

---

CONTRIBUTING.md
ImageMetaTag/db.py
test.py

Added Paul Earnshaw to see if that fixes the error on his pull request #85.

A couple of minor pylint tweaks, added Paul Earnshaw to contributors

---

ImageMetaTag/webpage.py
test.css
test.py

The default styling of the resulting webpage may not be to everyones liking so have added the option to supply a user css file.

Added option to supply a css file to style the webpage, included test.

---

ImageMetaTag/img_dict.py

Previous sort was to restrictive on the None string.

Deal with all variants of None in a T+ string

---

ImageMetaTag/img_dict.py
docs/build/html/_modules/ImageMetaTag/img_dict.html
docs/build/html/_modules/ImageMetaTag/savefig.html
docs/build/html/_static/jquery-1.11.1.js
docs/build/html/_static/underscore-1.3.1.js
test.py

Problems with the last few releases all relate to changes, and subsequent errors, in the ImageDict.sort_keys method.
Properly testing the method in the test.py script will make it easier to make changes to the sorting in future, and hopefully catch the errors much sooner.

Added new test to ensure that ImageDict.sort_keys() works as intended

---

ImageMetaTag/db.py
ImageMetaTag/img_dict.py
ImageMetaTag/savefig.py
ImageMetaTag/webpage.py
simplest_img_dict.py
test.py

Occasional review of changes with pylint - using the standard/default pylint config (rather than pep8) this gives a good score of 9.34.

pylint cosmetic changes only

---

test.py

Added option to test.py for minimal testing (--minimal) which could be used in integration tests etc.
This does not cover any actual testing, just sets up the --minimal option.

Option to test.py for minimal testing (--minimal)

---

ImageMetaTag/db.py
docs/build/html/_modules/ImageMetaTag.html
test.py

A useful option for working on code to process large databases of millions of images, by allowing you to work with a random subsample of images for development in a memory/cpu efficient way.

Added option to read a random sample of images from database

---

ImageMetaTag/webpage.py

Web load errmsg

---

ImageMetaTag/db.py

Prev. commit needed an add_command as well.

Add the add_command after creating table

---

setup.py

attempt to have bin directory available

---

ImageMetaTag/webpage.py
bin/rm_imt_images

Simple tweak to the delete request

rm_imt_images more informative delete permission request

---

ImageMetaTag/javascript/imt_dropdown.js
ImageMetaTag/webpage.py

Added a default image slider position set by, of course, a simple slider.

Slider position has a slidable default.

---

ImageMetaTag/javascript/imt_dropdown.js
ImageMetaTag/webpage.py
test.py

Added the option to still show the last image, when it's being used as a slider

last_img_still_show added for the last image slider option

---

README.md

Updated URL of the docs in their new location

Updated URL to the new documentation
