MetOffice/image-meta-tag

- lib/ImageMetaTag/img_dict.py
- lib/ImageMetaTag/webpage.py
- test.py
As part of issue #6 the large arrays of file locations have been reduced in size by referencing a list of subdirectories (and removing whitespace that gave nice formatting when reading html, but did nothing).
> Issue #6 recude webpage filesizes by referencing a list of subdirectories

- lib/ImageMetaTag/img_dict.py
- test.py
This fixes a bug in the test for an image being used in a multi-image selector: only the last one would count.
Fixing the bug broke the test.py script as it relied on it to prevent duplicate testing.
> Fix to a bug testing for the first image in a multi-selector

- lib/ImageMetaTag/db.py
- test.py
Added options to read_img_info_from_dbfile , to enable it to return more memory efficient dict.
These options are:
1. filtering the metadata tags that are returned to the those specified in a list (and failing if not all of these are present).
1. listing the strings used as a metadata tag, and returning the output dictionary containing only references to the strings in that list (as duplication is common).
> More memory efficient dict from read_img_info_from_dbfile

- lib/ImageMetaTag/__init__.py
- lib/ImageMetaTag/db.py
- lib/ImageMetaTag/img_dict.py
- lib/ImageMetaTag/webpage.py
- test.py
This code works to add selector names above the drop down menus on the output webpages.
test.py script modified to include a page with labels, and this works well. Resultant webpages have only minor differneces and these are tested with firefox and internet explorer.
Included a pylint tidyup of a few recent changes at the end.
> Add selector names to web pages

- lib/ImageMetaTag/webpage.py
A couple of line breaks looked bad once selector/level names were included, so tightening the layout.
> Slightly tigher page layout

- docs/build/html/ImageMetaTagDocs
Symlink was accidentally created when setting up internal version of documentation and is not neded
> Deleted symlink added by mistake

- lib/ImageMetaTag/img_dict.py
- lib/ImageMetaTag/savefig.py
- lib/ImageMetaTag/webpage.py
Simple to change, as we were already importing from PIL for ImageChops this reduced dependencies rather than adds to them.
> Move to using PIL.Image rather than the old Image library

- ImageMetaTag/savefig.py
So a text is needed to catch the error if using to/from byte.
> Older versions of PIL need tostring instead

- ImageMetaTag/db.py
- ImageMetaTag/savefig.py
A minor change - the file name of the affected db file is written out when an SQL operational error is raised.
> sql errors also include the file affected when raised

- ImageMetaTag/__init__.py
- ImageMetaTag/savefig.py
If any image post-processing is required, the savefig command will now save to an IO buffer in memory, rather than to an initial file (which would then need to be read in, and usually overwritten).
Testing shows this change does not noticeably speed up writing out the images, but it should reduce the disk load on any systems doing a lot of plotting.
> Img save to mem

- .gitignore
- setup.py
Conda needs the javascript to be in a package_dir, but this broke setup.py for non-conda isntall. This hopefully fixes that, while conda hopefully still works.
Merging to master, and will test non-conda installs again. If it works, then hopefully conda won't be broken on the next release!
> Fix to installing outside conda

- ImageMetaTag/webpage.py
Errant print statement removed when writing a webpage with optgroups.
> errant print statement left in from optgroups

- release_process
Needs twine installed to do an upload to pypi, but that can be done in a conda environment.
> Updated release process to add to pypi

- ImageMetaTag/db.py
Reports disk IO errors separately to other sqlite3 OperationalError messages. A parallel task might have just deleted the file, or something similar.
> Better error trapping for database deletes

- ImageMetaTag/img_dict.py
Negative values of forecast lead time now sorted for correcly in ImageDict.sort_keys().
This is an example where fixing issue #95 would allow this to be fixed in user/application specific code rather than in the library.
> Forecast lead time string changed to deal with negative values

- ImageMetaTag/img_dict.py
Having T+None in a list of lead-times was broken.
This changes allows T+None to be sorted (always comes last)
> Fix for T+None for sorting image dict keys

- ImageMetaTag/savefig.py
Adds reserved header names, so that converting jpg images to png works in postproc.
Ideally, need to correctly identify and tag jpg images...
> Jpg postproc

- ImageMetaTag/db.py
Quick fix for empty database files (occasionally created when running large processes in parallel).
> Quick fix for empty database files

- bin/rm_imt_images.py
Adds a bin directory to the directory structure, containing a useful tool to delete files from both disk and a ImageMetaTag image database in a consistent way.
The bin directory will need to be checked for the different package distribution methods etc, but that is a separate issue.
> rm_imt_image.py

- ImageMetaTag/img_dict.py
- test.py
Catches non-numeric strings included in a numeric set of levels that start with E or e.
These would catch the previous regex and it would try and convert these strings to a float.
> Sorting fix

- ImageMetaTag/savefig.py
Image.ANTIALIAS was deprecated prior to pillow v9.4, but also removed at v10. Therefore ImageMetaTag will not be able to produce thumbnail images when used in combination with pillow v10 or above. This change applies the suggested fix of using Image.LANCZOS instead.
> Use Image.LANCZOS instead of Image.ANTIALIAS for thumbnails
